name: Simulate NPM Downloads

on:
  schedule:
    - cron: '0 * * * *'  # Runs every 6 hours (UTC)
  workflow_dispatch:       # Manual run support

jobs:
  simulate-install:
    runs-on: ubuntu-latest
    steps:
      - name: Install from NPM (counts as download)
        run: |
          mkdir test-npm
          cd test-npm
          npm init -y
          npm install nextgen-mft-ai
